sudo: required

language: python
python:
  - "3.6"  # required, otherwise conda will try to clash with py2 packages

before_install:
  # Get and install anaconda (https://conda.io/docs/travis.html)
  - wget -nv https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a  # Useful for debugging any issues with conda

install:
  - export PACKAGE_NAME=multiqc
  - conda config --add channels defaults --add channels vladsaveliev --add channels bioconda --add channels conda-forge
  - conda install python=$TRAVIS_PYTHON_VERSION pip requests conda-build jinja2 anaconda-client
  # Building package
  - conda build conda_pkg/${PACKAGE_NAME}
  - conda install --use-local ${PACKAGE_NAME}

script:
  - multiqc --version

deploy:
  # Deploy to Anaconda.org
  - provider: script
    script:
      anaconda -t ${ANACONDA_TOKEN} upload $HOME/miniconda/conda-bld/noarch/${PACKAGE_NAME}-*.tar.bz2
    skip_cleanup: true
