#################################################################
# MultiQC Defaults
#################################################################
# This file contains the default configuration options
# for MultiQC. IT SHOULD NOT BE EDITED. If you want to
# change any of these config options, create a new file
# in any of the following locations:
#  1. <installation_dir>/multiqc_config.yaml (not pip or conda)
#  2. ~/.multiqc_config.yaml
#  3. <working directory>/multiqc_config.yaml
#################################################################

title: null
subtitle: null
intro_text: null
custom_message: null
report_header_info: null
config_file: null
custom_logo: null
custom_logo_url: null
custom_logo_title: null
simple_output: false
template: 'default'
pandoc_template: null
output_fn_name: 'multiqc_report.html'
data_dir_name: 'multiqc_data'
plots_dir_name: 'multiqc_plots'
data_format: 'tsv'

force: false
prepend_dirs: false
prepend_dirs_depth: 0
prepend_dirs_sep: ' | '
file_list: false
make_data_dir: true
zip_data_dir: false
export_plots: false
plots_force_flat: false
plots_force_interactive: false
plots_flat_numseries: 100
num_datasets_plot_limit: 50
max_table_rows: 500
table_columns_visible: {}

fn_ignore_dirs: []
fn_ignore_paths: []
no_version_check: false
log_filesize_limit: 5000000
report_readerrors: false
report_imgskips: false
skip_generalstats: false
data_format_extensions:
    tsv: 'txt'
    json: 'json'
    yaml: 'yaml'
export_plot_formats:
    - 'png'
    - 'svg'
    - 'pdf'

# Option to disable sample name cleaning if desired
fn_clean_sample_names: true

# Used for cleaning sample names. Should be strings.
# NB: These are removed in order!
fn_clean_exts:
    - '.gz'
    - '.fastq'
    - '.fq'
    - '.bam'
    - '.sam'
    - '.sra'
    - '.vcf'
    - '.dat'
    - '_tophat'
    - '.log'
    - '.stderr'
    - '.out'
    - 'Log.final'
    - '.flagstat'
    - '_star_aligned'
    - '_fastqc'
    - '.hicup'
    - '.counts'
    - '_counts'
    - '.txt'
    - '.aligned'
    - 'Aligned'
    - '.merge'
    - '.deduplicated'
    - '.dedup'
    - '.clean'
    - '.sorted'
    - '.report'
    - '| stdin'
# These are removed after the above, only if sample names
# start or end with this string. Again, removed in order.
fn_clean_trim:
    - '.'
    - ':'
    - '_'
    - '-'
    - '.r'
    - '_val'

# Files to ignore when indexing files.
# Grep file match patterns.
fn_ignore_files:
    - '.DS_Store'
    - '*.bam'
    - '*.sam'
    - '*.fq.gz'
    - '*.fastq.gz'
    - '*.fq'
    - '*.fastq'
    - '*.gtf'
    - '*.bed'
    - '*.vcf'
    - '*.txt.gz'

# Order that modules should appear in report. Try to list in order of analysis,
# eg. FastQC is usually the first step, so should be last in this list.
module_order:
    # Post-alignment analysis results
    - 'quast'
    - 'snpeff'
    - 'qualimap'
    - 'rnaseq_az'
    - 'bcftools'
    - 'featureCounts'
    - 'methylQA'
    - 'rseqc'
    - 'picard'
    - 'preseq'
    - 'samblaster'
    - 'samtools'
    - 'bamtools'
    # Alignment tool stats
    - 'bismark'
    - 'hicup'
    - 'salmon'
    - 'kallisto'
    - 'star'
    - 'tophat'
    - 'bowtie2'
    - 'bowtie1'
    # Pre-alignment QC
    - 'cutadapt'
    - 'trimmomatic'
    - 'skewer'
    - 'fastq_screen'
    - 'fastqc'
    - 'targqc'
    - 'bcl2fastq'
